package gitops

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
)

// createPR opens a GitHub pull request and returns the PR HTML URL.
func (g *GitHubGitOps) createPR(ctx context.Context, branchName string, req PRRequest, diff string) (string, error) {
	title := fmt.Sprintf("fix: auto-remediate %s for %s", req.Diag.FailureType, req.Event.PodName)
	body := buildPRBody(req, diff)

	prReq := map[string]string{
		"title": title,
		"body":  body,
		"head":  branchName,
		"base":  "main",
	}

	reqBytes, err := json.Marshal(prReq)
	if err != nil {
		return "", fmt.Errorf("createPR: marshal request: %w", err)
	}

	url := fmt.Sprintf("%s/repos/%s/pulls", g.baseGitHubURL, g.gitOpsRepo)
	httpReq, err := http.NewRequestWithContext(ctx, http.MethodPost, url, bytes.NewReader(reqBytes))
	if err != nil {
		return "", fmt.Errorf("createPR: build request: %w", err)
	}
	httpReq.Header.Set("Authorization", "token "+g.githubToken)
	httpReq.Header.Set("Content-Type", "application/json")
	httpReq.Header.Set("Accept", "application/vnd.github.v3+json")

	resp, err := g.httpClient.Do(httpReq)
	if err != nil {
		return "", fmt.Errorf("createPR: http request: %w", err)
	}
	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", fmt.Errorf("createPR: read response: %w", err)
	}

	if resp.StatusCode != http.StatusCreated {
		snippet := respBody
		if len(snippet) > 500 {
			snippet = snippet[:500]
		}
		return "", fmt.Errorf("createPR: unexpected status %d: %s", resp.StatusCode, string(snippet))
	}

	var prResp struct {
		HTMLURL string `json:"html_url"`
	}
	if err := json.Unmarshal(respBody, &prResp); err != nil {
		return "", fmt.Errorf("createPR: unmarshal response: %w", err)
	}

	return prResp.HTMLURL, nil
}

// buildPRBody constructs the PR body from the request and diff.
func buildPRBody(req PRRequest, diff string) string {
	body := fmt.Sprintf(`## Automated Remediation

**Failure detected:** %s on pod %s at %s
**Root cause:** %s
**Proposed fix:** %s changed to %s

### Agent Reasoning
%s`,
		req.Diag.FailureType,
		req.Event.PodName,
		req.Event.Timestamp.String(),
		req.Diag.RootCause,
		req.Diag.PatchType,
		req.Diag.PatchValue,
		req.Diag.ReasoningSummary,
	)

	if diff != "" {
		body += "\n\n### Patch Diff\n```diff\n" + diff + "\n```"
	}

	body += "\n\n---\n*Generated by gitops-remediator. Review before merging.*"
	return body
}
